- name: "Create user 'ansible'"
  ansible.builtin.user:
    name: "ansible"
    state: present
    create_home: yes
  become: true

- name: "Update ssh keys of user 'ansible'"
  ansible.builtin.copy:
    dest: "/home/ansible/.ssh/authorized_keys"
    content: |
      {% for u in ssh_users %}
      {{ u.key }}
      {% endfor %}
    owner: ansible
    group: ansible
    mode: '0600'
  become: true